# Site
name: "coacervo"
title: "coacervo"
description: "Stuff about Coacervo."
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: ""
google_analytics: "UA-143608567-1"
disqus: "coacervo"
mailchimp-list:
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  daniel:
    name: Daniel Marsh-Patrick
    display_name: Daniel Marsh-Patrick
    gravatar: 0b57cf928c302b4c199c7fe56235c553
    email: daniel@coacervo.co
    web: /about
    bluesky: https://bsky.app/profile/dm-p.nz
    linkedin: https://www.linkedin.com/in/daniel-m-p/
    github: https://github.com/dm-p
    description: "Stuff about Daniel."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
